import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import  SessionProvider  from "@/store/SessionProvider";
import { getServerSession } from "next-auth";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession()
  return (
    <html lang="en">  
      <body className={inter.className}>
        <SessionProvider session={session}>
        <div className="mx-auto text-2xl max-w-5xl mb-10 gap-2">
          <Header/>
          {children}
        </div>
        </SessionProvider>
       </body>
    </html>
  );
}
